### ISSUE TITLE
can't build cu_birds

### ISSUE THREAD

**Issue by brando90** [brando90/pytorch-meta-dataset#16]
error:
```
(metalearning_gpu) brando9~ $ python -m meta_dataset.dataset_conversion.convert_datasets_to_records \
>   --dataset=aircraft \
>   --aircraft_data_root=$MDS_DATA_PATH/fgvc-aircraft-2013b \
>   --splits_root=$SPLITS \
>   --records_root=$RECORDS
2023-01-04 14:25:53.171855: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-04 14:25:54.916863: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.7/lib64:/usr/local/cuda-11.7/lib64:/usr/local/cuda-11.7/lib64:/usr/local/cuda-11.7/lib64:
2023-01-04 14:25:54.917012: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.7/lib64:/usr/local/cuda-11.7/lib64:/usr/local/cuda-11.7/lib64:/usr/local/cuda-11.7/lib64:
2023-01-04 14:25:54.917033: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-01-04 14:25:57.822182: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.7/lib64:/usr/local/cuda-11.7/lib64:/usr/local/cuda-11.7/lib64:/usr/local/cuda-11.7/lib64:
2023-01-04 14:25:57.822278: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
I0104 14:25:57.823218 140230994076288 convert_datasets_to_records.py:151] Creating FGVC-Aircraft Benchmark specification and records in directory /lfs/ampere4/0/brando9/data/mds/records/aircraft...
I0104 14:25:57.823542 140230994076288 dataset_to_records.py:649] Attempting to read splits from /lfs/ampere4/0/brando9/data/mds/splits/aircraft_splits.json...
I0104 14:25:57.824719 140230994076288 dataset_to_records.py:661] Unsuccessful.
I0104 14:25:57.852395 140230994076288 dataset_to_records.py:233] Created splits with 70 train, 15 validation and 15 test classes.
Traceback (most recent call last):
  File "/dfs/scratch0/brando9/anaconda/envs/metalearning_gpu/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/dfs/scratch0/brando9/anaconda/envs/metalearning_gpu/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/afs/cs.stanford.edu/u/brando9/diversity-for-predictive-success-of-meta-learning/meta-dataset/meta_dataset/dataset_conversion/convert_datasets_to_records.py", line 157, in <module>
    tf.app.run(main)
  File "/dfs/scratch0/brando9/anaconda/envs/metalearning_gpu/lib/python3.9/site-packages/tensorflow/python/platform/app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/dfs/scratch0/brando9/anaconda/envs/metalearning_gpu/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/dfs/scratch0/brando9/anaconda/envs/metalearning_gpu/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/afs/cs.stanford.edu/u/brando9/diversity-for-predictive-success-of-meta-learning/meta-dataset/meta_dataset/dataset_conversion/convert_datasets_to_records.py", line 153, in main
    converter.convert_dataset()
  File "/afs/cs.stanford.edu/u/brando9/diversity-for-predictive-success-of-meta-learning/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 610, in convert_dataset
    self.create_dataset_specification_and_records()
  File "/afs/cs.stanford.edu/u/brando9/diversity-for-predictive-success-of-meta-learning/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 1172, in create_dataset_specification_and_records
    splits = self.get_splits()
  File "/afs/cs.stanford.edu/u/brando9/diversity-for-predictive-success-of-meta-learning/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 698, in get_splits
    splits = self.create_splits()
  File "/afs/cs.stanford.edu/u/brando9/diversity-for-predictive-success-of-meta-learning/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 1157, in create_splits
    variants = [line.strip() for line in f.readlines() if line]
  File "/dfs/scratch0/brando9/anaconda/envs/metalearning_gpu/lib/python3.9/site-packages/tensorflow/python/lib/io/file_io.py", line 174, in readlines
    self._preread_check()
  File "/dfs/scratch0/brando9/anaconda/envs/metalearning_gpu/lib/python3.9/site-packages/tensorflow/python/lib/io/file_io.py", line 77, in _preread_check
    self._read_buf = _pywrap_file_io.BufferedInputStream(
tensorflow.python.framework.errors_impl.NotFoundError: /lfs/ampere4/0/brando9/data/mds/fgvc-aircraft-2013b/data/variants.txt; No such file or directory
```

did you try building a few data points like we agreed?

**Comment by patricks-lab** [comment]
odd - it seems like above that's fgvc aircraft and not cubirds, not sure what's going on. 

Just tried the cubirds which seems fine w/ my new script and python reqs list - maybe try with my updated script just wrote here which I found to work with installing cubirds: https://github.com/brando90/pytorch-meta-dataset/issues/12#issuecomment-1371929062?
