### ISSUE TITLE
aircraft does not convert to record

### ISSUE THREAD

**Issue by brando90** [brando90/pytorch-meta-dataset#17]
error:
```
attributes.txt  CUB_200_2011  CUB_200_2011.tgz  dtd-r1.0.1.tar.gz  fgvc-aircraft-2013b  fgvc-aircraft-2013b.tar.gz  omniglot  records  splits
(metalearning_gpu) brando9~/data/mds $ python -m meta_dataset.dataset_conversion.convert_datasets_to_records \
>   --dataset=aircraft \
>   --aircraft_data_root=$MDS_DATA_PATH/fgvc-aircraft-2013b \
>   --splits_root=$SPLITS \
>   --records_root=$RECORDS
2023-01-04 15:13:38.475933: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-04 15:13:39.933260: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.7/lib64:/usr/local/cuda-11.7/lib64:/usr/local/cuda-11.7/lib64:/usr/local/cuda-11.7/lib64:
2023-01-04 15:13:39.933345: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.7/lib64:/usr/local/cuda-11.7/lib64:/usr/local/cuda-11.7/lib64:/usr/local/cuda-11.7/lib64:
2023-01-04 15:13:39.933356: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-01-04 15:13:42.441385: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.7/lib64:/usr/local/cuda-11.7/lib64:/usr/local/cuda-11.7/lib64:/usr/local/cuda-11.7/lib64:
2023-01-04 15:13:42.441435: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
I0104 15:13:42.441903 139979644949120 convert_datasets_to_records.py:151] Creating FGVC-Aircraft Benchmark specification and records in directory /lfs/ampere4/0/brando9/data/mds/records/aircraft...
I0104 15:13:42.442091 139979644949120 dataset_to_records.py:649] Attempting to read splits from /lfs/ampere4/0/brando9/data/mds/splits/aircraft_splits.json...
I0104 15:13:42.442540 139979644949120 dataset_to_records.py:661] Unsuccessful.
I0104 15:13:42.443071 139979644949120 dataset_to_records.py:233] Created splits with 70 train, 15 validation and 15 test classes.
I0104 15:13:42.443794 139979644949120 dataset_to_records.py:701] Saving new splits for dataset aircraft at /lfs/ampere4/0/brando9/data/mds/splits/aircraft_splits.json...
I0104 15:13:42.444231 139979644949120 dataset_to_records.py:705] Done.
I0104 15:13:42.658740 139979644949120 dataset_to_records.py:1231] Creating record for class ID 0 (A340-300)...
Traceback (most recent call last):
  File "/dfs/scratch0/brando9/anaconda/envs/metalearning_gpu/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/dfs/scratch0/brando9/anaconda/envs/metalearning_gpu/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/afs/cs.stanford.edu/u/brando9/diversity-for-predictive-success-of-meta-learning/meta-dataset/meta_dataset/dataset_conversion/convert_datasets_to_records.py", line 157, in <module>
    tf.app.run(main)
  File "/dfs/scratch0/brando9/anaconda/envs/metalearning_gpu/lib/python3.9/site-packages/tensorflow/python/platform/app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/dfs/scratch0/brando9/anaconda/envs/metalearning_gpu/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/dfs/scratch0/brando9/anaconda/envs/metalearning_gpu/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/afs/cs.stanford.edu/u/brando9/diversity-for-predictive-success-of-meta-learning/meta-dataset/meta_dataset/dataset_conversion/convert_datasets_to_records.py", line 153, in main
    converter.convert_dataset()
  File "/afs/cs.stanford.edu/u/brando9/diversity-for-predictive-success-of-meta-learning/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 610, in convert_dataset
    self.create_dataset_specification_and_records()
  File "/afs/cs.stanford.edu/u/brando9/diversity-for-predictive-success-of-meta-learning/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 1247, in create_dataset_specification_and_records
    write_tfrecord_from_image_files(
  File "/afs/cs.stanford.edu/u/brando9/diversity-for-predictive-success-of-meta-learning/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 374, in write_tfrecord_from_image_files
    img = load_and_process_image(path, bbox)
  File "/afs/cs.stanford.edu/u/brando9/diversity-for-predictive-success-of-meta-learning/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 355, in load_and_process_image
    img = img.crop(bbox)
  File "/dfs/scratch0/brando9/anaconda/envs/metalearning_gpu/lib/python3.9/site-packages/PIL/Image.py", line 1206, in crop
    if box[2] < box[0]:
TypeError: 'map' object is not subscriptable
```

**Comment by patricks-lab** [comment]
issue here appears to be due to a really new version of pillow: https://github.com/jsvine/pdfplumber/discussions/637

looks like doing "pip install pillow==9.0" resolved it for me in my test. (effectively I had to downgrade from 9.4->9.0)
