### ISSUE TITLE
traffic_sign gives error, image not found?

### ISSUE THREAD

**Issue by brando90** [brando90/pytorch-meta-dataset#19]
```
(mds_env_gpu) brando9~ $ python -m meta_dataset.dataset_conversion.convert_datasets_to_records \
>   --dataset=traffic_sign \
>   --traffic_sign_data_root=$MDS_DATA_PATH/GTSRB \
>   --splits_root=$SPLITS \
>   --records_root=$RECORDS

2023-01-05 15:53:33.462105: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.7/lib64:/usr/local/cuda-11.7/lib64:
2023-01-05 15:53:33.462140: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
I0105 15:53:33.462812 140581859123840 convert_datasets_to_records.py:151] Creating Traffic Sign specification and records in directory /lfs/ampere4/0/brando9/data/mds/records/traffic_sign...
I0105 15:53:33.462960 140581859123840 dataset_to_records.py:649] Attempting to read splits from /lfs/ampere4/0/brando9/data/mds/splits/traffic_sign_splits.json...
I0105 15:53:33.463387 140581859123840 dataset_to_records.py:661] Unsuccessful.
I0105 15:53:33.465234 140581859123840 dataset_to_records.py:701] Saving new splits for dataset traffic_sign at /lfs/ampere4/0/brando9/data/mds/splits/traffic_sign_splits.json...
I0105 15:53:33.471390 140581859123840 dataset_to_records.py:705] Done.
I0105 15:53:33.471474 140581859123840 dataset_to_records.py:1308] Creating record for class ID 0 (00.Speed limit (20km/h))...
Traceback (most recent call last):
  File "/lfs/ampere4/0/brando9/miniconda/envs/mds_env_gpu/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/lfs/ampere4/0/brando9/miniconda/envs/mds_env_gpu/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/afs/cs.stanford.edu/u/brando9/diversity-for-predictive-success-of-meta-learning/meta-dataset/meta_dataset/dataset_conversion/convert_datasets_to_records.py", line 157, in <module>
    tf.app.run(main)
  File "/lfs/ampere4/0/brando9/miniconda/envs/mds_env_gpu/lib/python3.9/site-packages/tensorflow/python/platform/app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/lfs/ampere4/0/brando9/miniconda/envs/mds_env_gpu/lib/python3.9/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/lfs/ampere4/0/brando9/miniconda/envs/mds_env_gpu/lib/python3.9/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/afs/cs.stanford.edu/u/brando9/diversity-for-predictive-success-of-meta-learning/meta-dataset/meta_dataset/dataset_conversion/convert_datasets_to_records.py", line 153, in main
    converter.convert_dataset()
  File "/afs/cs.stanford.edu/u/brando9/diversity-for-predictive-success-of-meta-learning/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 610, in convert_dataset
    self.create_dataset_specification_and_records()
  File "/afs/cs.stanford.edu/u/brando9/diversity-for-predictive-success-of-meta-learning/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 1322, in create_dataset_specification_and_records
    self.images_per_class[class_id] = write_tfrecord_from_directory(
  File "/afs/cs.stanford.edu/u/brando9/diversity-for-predictive-success-of-meta-learning/meta-dataset/meta_dataset/dataset_conversion/dataset_to_records.py", line 418, in write_tfrecord_from_directory
    filenames = sorted(tf.io.gfile.listdir(class_directory))
  File "/lfs/ampere4/0/brando9/miniconda/envs/mds_env_gpu/lib/python3.9/site-packages/tensorflow/python/lib/io/file_io.py", line 766, in list_directory_v2
    raise errors.NotFoundError(
tensorflow.python.framework.errors_impl.NotFoundError: Could not find directory /lfs/ampere4/0/brando9/data/mds/GTSRB/Final_Training/Images/00000
```

**Comment by brando90** [comment]
re do it
